/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

/**
 *
 * @author TMK_PLAN4
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    GridBagLayout layout = new GridBagLayout();
    MainAdmin mainadmin; // trang admin
    //HomePicture homepicture;
    Teacher teacher;

    public Home() {
        initComponents();
        // CurrentTime();// hien thi thoi gian dang nhap
        //lbName.setText(UserInFormation.name); // show user name login
        destophomeBottom.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        mainadmin = new MainAdmin();
        c.gridx = 0;
        c.gridy = 0;
        destophomeBottom.add(mainadmin, c);
        mainadmin.setVisible(false);

        teacher = new Teacher();
        c.gridx = 0;
        c.gridy = 0;
        destophomeBottom.add(teacher, c);
        teacher.setVisible(false);

        /* 
        menuAdmin.setVisible(false); // to hide menuAdmin cho toi khi dang nhap
        menuTeacher.setVisible(false); // to hide menuTeacher cho toi khi dang nhap
        menuStudent.setVisible(false); // to hide menuStudent cho toi khi dang nhap
        Login lg = new Login();// to show login 
        lg.setVisible(true); // to show login
         */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destophome = new javax.swing.JPanel();
        destophomeBottom = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuswitch = new javax.swing.JMenuItem();
        menuthoat = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quiz System Online");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        destophome.setLayout(new java.awt.BorderLayout());

        destophomeBottom.setMinimumSize(new java.awt.Dimension(1350, 685));

        javax.swing.GroupLayout destophomeBottomLayout = new javax.swing.GroupLayout(destophomeBottom);
        destophomeBottom.setLayout(destophomeBottomLayout);
        destophomeBottomLayout.setHorizontalGroup(
            destophomeBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1350, Short.MAX_VALUE)
        );
        destophomeBottomLayout.setVerticalGroup(
            destophomeBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        destophome.add(destophomeBottom, java.awt.BorderLayout.CENTER);

        getContentPane().add(destophome, java.awt.BorderLayout.CENTER);

        menuFile.setText("File");
        menuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFileActionPerformed(evt);
            }
        });

        menuswitch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/EntityDataModel_association_16x16.png"))); // NOI18N
        menuswitch.setText("Switch User");
        menuswitch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuswitchActionPerformed(evt);
            }
        });
        menuFile.add(menuswitch);

        menuthoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/GoRtlHS.png"))); // NOI18N
        menuthoat.setText("Exit");
        menuthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuthoatActionPerformed(evt);
            }
        });
        menuFile.add(menuthoat);

        jMenuBar2.add(menuFile);

        menuHelp.setText("Help");

        jMenuItem1.setText("About Us");
        menuHelp.add(jMenuItem1);

        jMenuBar2.add(menuHelp);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   // tao role

    public void AssignMenu(String role) {
        if (role.equals("admin")) {
            mainadmin.setVisible(true);
            menuFile.setVisible(true);
            teacher.setVisible(false);
            menuHelp.setVisible(true);
        } else if (role.equals("teacher")) {
            mainadmin.setVisible(false);
            menuFile.setVisible(true);
            teacher.setVisible(true);
            menuHelp.setVisible(true);
        } else if (role.equals("student")) {
            mainadmin.setEnabled(false);
            menuFile.setVisible(true);
            teacher.setVisible(false);
            menuHelp.setVisible(true);
        }
    }

    private void menuthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuthoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuthoatActionPerformed

    private void menuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFileActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_menuFileActionPerformed

    private void menuswitchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuswitchActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_menuswitchActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel destophome;
    private javax.swing.JPanel destophomeBottom;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuHelp;
    private javax.swing.JMenuItem menuswitch;
    private javax.swing.JMenuItem menuthoat;
    // End of variables declaration//GEN-END:variables
}
