/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAOT.QuestionDAO;
import DAOT.SubjectDAO;
import DAOT.UserInformation;
import DAOT.alert_messager;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.usermodel.DataFormatter;
import org.apache.poi.ss.usermodel.Row;

/**
 *
 * @author TMK_PLAN4
 */
public class Question extends javax.swing.JInternalFrame {

    /**
     * Creates new form Question
     */
    private DefaultTableModel model = null;
    private int selectedRow = -1;
    alert_messager alt = new alert_messager();

    public Question() {
        initComponents();
        model = new DefaultTableModel(null, new Object[]{"Question ID", "Question Content", "Level", "Aswer A", "Answer B",
            "Answer C", "Answer D", "CorrectAnswer", "Subject ID", "User ID", "Status"});
        tblques.setModel(model);
        loadDataToTable(); // load data len table
        LoadSubjectToCBO(); // load data len combox Subject
        lbuserid.setText(String.valueOf(UserInformation.userID));

    }

    // lam moi 
    private void RefreshForm() {
        txtquescontent.setText("");
        txtselectA.setText("");
        txtselectB.setText("");
        txtselectC.setText("");
        txtselectD.setText("");
        cbsuject.setSelectedIndex(0);
        cbocorrectAnswer.setSelectedIndex(0);
        cbolevel.setSelectedIndex(0);
        lbquestionID.setText("");

    }

    // load data to combox
    private void LoadSubjectToCBO() {

        SubjectDAO dao = new SubjectDAO();
        ResultSet rs = dao.loadData();
        try {
            while (rs.next()) {
                cbsuject.addItem(rs.getString("tenmonhoc"));
            }
            rs.close();

        } catch (Exception e) {
            System.out.println("GUI.GiaoVien.Question.LoadSubjectToCBO() : " + e.getMessage());
        }
    }

    public void loadDataToTable() {
        model = new DefaultTableModel(null, new Object[]{"Question ID", "Question Content", "Level", "Aswer A", "Answer B",
            "Answer C", "Answer D", "CorrectAnswer", "Subject ID", "User ID", "Status"});
        QuestionDAO dao = new QuestionDAO();
        ResultSet rs = dao.loadData();
        try {

            while (rs.next()) {
                model.addRow(new Object[]{rs.getInt("macauhoi"), rs.getString("ndcauhoi"), rs.getInt("dokho"),
                    rs.getString("phuonganA"), rs.getString("phuonganB"), rs.getString("phuonganC"), rs.getString("phuonganD"), rs.getString("dapan"), rs.getString("mamonhoc"), rs.getInt("matk"),
                    rs.getInt("trangthai")});
            }
            tblques.setModel(model);
            rs.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnquestiontop = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtselectA = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtselectB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtselectC = new javax.swing.JTextField();
        txtselectD = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbolevel = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnimport = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        btnref = new javax.swing.JButton();
        cbocorrectAnswer = new javax.swing.JComboBox<>();
        cbsuject = new javax.swing.JComboBox<>();
        lbuserid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbquestionID = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtquescontent = new javax.swing.JTextArea();
        pnquestionbottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblques = new javax.swing.JTable();

        setIconifiable(true);
        setTitle("Create Question");
        setMinimumSize(new java.awt.Dimension(1350, 685));
        setPreferredSize(new java.awt.Dimension(1350, 685));
        setVisible(true);

        pnquestiontop.setMinimumSize(new java.awt.Dimension(1150, 230));
        pnquestiontop.setPreferredSize(new java.awt.Dimension(1150, 230));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Question");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("(*)");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Answer A");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("(*)");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Answer B");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("(*)");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Answer C");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("(*)");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("(*)");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Answer D");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Subject");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Level");

        cbolevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("(*)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("(*)");

        btnadd.setForeground(new java.awt.Color(102, 102, 102));
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1494135356_document-new.png"))); // NOI18N
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setForeground(new java.awt.Color(102, 102, 102));
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1494135526_compose.png"))); // NOI18N
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setForeground(new java.awt.Color(102, 102, 102));
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1494188946_flat-style-circle-delete-trash.png"))); // NOI18N
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnimport.setForeground(new java.awt.Color(102, 102, 102));
        btnimport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1494218183_excel.png"))); // NOI18N
        btnimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimportActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Create By");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Correct Answer");

        btnref.setForeground(new java.awt.Color(102, 102, 102));
        btnref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        btnref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefActionPerformed(evt);
            }
        });

        cbocorrectAnswer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--", "A", "B", "C", "D" }));

        cbsuject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select--" }));

        lbuserid.setText("jLabel1");

        jLabel1.setText("QuesID");

        txtquescontent.setColumns(20);
        txtquescontent.setLineWrap(true);
        txtquescontent.setRows(5);
        txtquescontent.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtquescontent);

        javax.swing.GroupLayout pnquestiontopLayout = new javax.swing.GroupLayout(pnquestiontop);
        pnquestiontop.setLayout(pnquestiontopLayout);
        pnquestiontopLayout.setHorizontalGroup(
            pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnquestiontopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(pnquestiontopLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnquestiontopLayout.createSequentialGroup()
                            .addComponent(btnref)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnadd)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnimport)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnupdate)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btndelete))
                        .addGroup(pnquestiontopLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lbquestionID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel19)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbsuject, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cbolevel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(31, 31, 31)
                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnquestiontopLayout.createSequentialGroup()
                        .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)))
                    .addGroup(pnquestiontopLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnquestiontopLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbuserid)
                        .addGap(67, 67, 67)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbocorrectAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtselectA, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                    .addComponent(txtselectB)
                    .addComponent(txtselectC)
                    .addComponent(txtselectD))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnquestiontopLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnadd, btndelete, btnimport, btnref, btnupdate});

        pnquestiontopLayout.setVerticalGroup(
            pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnquestiontopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnquestiontopLayout.createSequentialGroup()
                        .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnquestiontopLayout.createSequentialGroup()
                                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(txtselectA, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(txtselectB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtselectC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtselectD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(jLabel16)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(cbolevel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(cbsuject, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(lbquestionID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnquestiontopLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9)))
                .addGap(18, 18, 18)
                .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnadd)
                        .addComponent(btnupdate)
                        .addComponent(btndelete)
                        .addComponent(btnref, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnimport, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel23)
                    .addGroup(pnquestiontopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(lbuserid))
                    .addComponent(cbocorrectAnswer))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pnquestiontopLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnadd, btndelete, btnimport, btnref, btnupdate});

        getContentPane().add(pnquestiontop, java.awt.BorderLayout.PAGE_START);

        pnquestionbottom.setLayout(new java.awt.BorderLayout());

        tblques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Question ID", "Question Content", "level", "Answer A", "Answer B", "Answer C", "Answer D", "Correct Answer", "Subject ID", "Create By"
            }
        ));
        tblques.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblquesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblques);

        pnquestionbottom.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnquestionbottom, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefActionPerformed
        RefreshForm();
    }//GEN-LAST:event_btnrefActionPerformed

    private void tblquesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquesMouseClicked
        // TODO add your handling code here:
        try {

            // get text tu bang 
            int row = tblques.getSelectedRow();
            int questionID = (Integer) model.getValueAt(row, 0);
            String questionContent = (String) model.getValueAt(row, 1);
            int level = (Integer) model.getValueAt(row, 2);
            String selectA = (String) model.getValueAt(row, 3);
            String selectB = (String) model.getValueAt(row, 4);
            String selectC = (String) model.getValueAt(row, 5);
            String selectD = (String) model.getValueAt(row, 6);
            String correctAnswer = (String) model.getValueAt(row, 7);
            String subjectID = (String) model.getValueAt(row, 8);
            int userID = (Integer) model.getValueAt(row, 9);
            int status = (Integer) model.getValueAt(row, 10);

            // xet text len cac o text fild
            txtquescontent.setText(questionContent);
            txtselectA.setText(selectA);
            txtselectB.setText(selectB);
            txtselectC.setText(selectC);
            txtselectD.setText(selectD);
            lbuserid.setText(String.valueOf(userID));
            lbquestionID.setText(String.valueOf(questionID));
            cbsuject.setSelectedItem(subjectID);
            cbolevel.setSelectedItem(String.valueOf(level));
            cbocorrectAnswer.setSelectedItem(correctAnswer);
        } catch (Exception e) {
            e.printStackTrace();
        }

        selectedRow = this.tblques.getSelectedRow();
    }//GEN-LAST:event_tblquesMouseClicked

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String questionContent = this.txtquescontent.getText();
        String answerA = this.txtselectA.getText();
        String answerB = this.txtselectB.getText();
        String answerC = this.txtselectC.getText();
        String answerD = this.txtselectD.getText();
        String subjectID = this.cbsuject.getSelectedItem().toString();
        String level = this.cbolevel.getSelectedItem().toString();
        String userID = lbuserid.getText().trim();
        String correctAnswer = this.cbocorrectAnswer.getSelectedItem().toString();
        if (questionContent.equals("")) {
            alt.alter(" you not yet fill in question content");
        } else if (subjectID.equals("--select--")) {
            alt.alter(" you not yet select subjectID");
        } else if (level.equals("--select--")) {
            alt.alter(" you not yet select level");
        } else if (answerA.equals("")) {
            alt.alter(" you not yet fill in answer A");
        } else if (answerB.equals("")) {
            alert_messager alt = new alert_messager();
            alt.alter(" you not yet fill in answer B");
        } else if (answerC.equals("")) {
            alt.alter(" you not yet fill in answer C");
        } else if (answerD.equals("")) {
            alt.alter(" you not yet fill in answer D");
        } else if (correctAnswer.equals("--select--")) {
            alt.alter(" you not yet select correct Answer");
        } else {

            DTO.Question dto = new DTO.Question();
            dto.setQuesion(questionContent);
            dto.setLevel(Integer.valueOf(level));
            dto.setMaMon(subjectID);
            dto.setAnsw1(answerA);
            dto.setAnsw2(answerB);
            dto.setAnsw3(answerC);
            dto.setAnsw4(answerD);
            dto.setDapan(this.cbocorrectAnswer.getSelectedItem().toString());
            dto.setMatk(Integer.valueOf(lbuserid.getText().trim()));
            QuestionDAO dao = new QuestionDAO();
            dao.inserQuestion(dto);
            alert_messager alt = new alert_messager();
            alt.alter("Insert successed!");
            loadDataToTable();
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please selecte a row to delete");
        } else {
            if (JOptionPane.showConfirmDialog(this, "Are you sure to delete?", "Deelte Warming", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                String id = lbquestionID.getText();
                QuestionDAO dao = new QuestionDAO();
                dao.deleteQuestion(id);
                alt.alter("Delete Success!!");
                loadDataToTable();
            } else {
                JOptionPane.showMessageDialog(this, "Deleted unsuccessfuly");
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        try {
            if (selectedRow == -1) {
                JOptionPane.showMessageDialog(this, "Please selecte a row want to update");
            } else {
                DTO.Question dto = new DTO.Question();
                dto.setId(lbquestionID.getText());
                dto.setQuesion(txtquescontent.getText());
                dto.setAnsw1(txtselectA.getText());
                dto.setAnsw2(txtselectB.getText());
                dto.setAnsw3(txtselectC.getText());
                dto.setAnsw4(txtselectD.getText());
                dto.setMaMon(String.valueOf(cbsuject.getSelectedItem().toString()));
                dto.setLevel(Integer.valueOf(cbolevel.getSelectedItem().toString()));
                dto.setDapan(String.valueOf(cbocorrectAnswer.getSelectedItem().toString()));

                QuestionDAO dao = new QuestionDAO();
                dao.updateQuestion(dto);
                alt.alter("update Successed !");
                loadDataToTable(); // sau khi update thanh cong se load du lieu len bang
            }
        } catch (Exception e) {

            alt.alter("Update not success");
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimportActionPerformed
        readExcel();
    }//GEN-LAST:event_btnimportActionPerformed
    public void readExcel() {
        JFileChooser dialog = new JFileChooser();
        int dialogResult = dialog.showOpenDialog(null);
        if (dialogResult == JFileChooser.OPEN_DIALOG) {
            String filePath = dialog.getSelectedFile().getPath();
            try {
                FileInputStream input = new FileInputStream(filePath);
                POIFSFileSystem fs = new POIFSFileSystem(input);
                HSSFWorkbook wb = new HSSFWorkbook(fs);
                DataFormatter formatter = new DataFormatter(Locale.US);
                HSSFSheet sheet = wb.getSheetAt(0);
                Row row;
                for (int i = 1; i <= sheet.getLastRowNum(); i++) {

                    row = sheet.getRow(i);

                    String question = formatter.formatCellValue(row.getCell(0));
                    int quesLevel = Integer.parseInt(formatter.formatCellValue(row.getCell(1)));
                    String subjectID = formatter.formatCellValue(row.getCell(2));
                    String anSw1 = formatter.formatCellValue(row.getCell(3));
                    String anSw2 = formatter.formatCellValue(row.getCell(4));
                    String anSw3 = formatter.formatCellValue(row.getCell(5));
                    String anSw4 = formatter.formatCellValue(row.getCell(6));
                    String anSwCorrect = formatter.formatCellValue(row.getCell(7));
                    int userID = Integer.valueOf(formatter.formatCellValue(row.getCell(8)));

                    DTO.Question dto = new DTO.Question(question, quesLevel, subjectID, anSw1, anSw2, anSw3, anSw4, anSwCorrect, userID);
                    QuestionDAO dao = new QuestionDAO();
                    dao.inserQuestion(dto);
                }
                alt.alter("Success import excel to mysql table");
                loadDataToTable(); // sau khi update thanh cong se load du lieu len bang
                input.close();
                System.out.println("Success import excel to mysql table");
            } catch (IOException e) {
                System.out.println("err : " + e.getMessage());
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnimport;
    private javax.swing.JButton btnref;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbocorrectAnswer;
    private javax.swing.JComboBox<String> cbolevel;
    private javax.swing.JComboBox<String> cbsuject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbquestionID;
    private javax.swing.JLabel lbuserid;
    private javax.swing.JPanel pnquestionbottom;
    private javax.swing.JPanel pnquestiontop;
    private javax.swing.JTable tblques;
    private javax.swing.JTextArea txtquescontent;
    private javax.swing.JTextField txtselectA;
    private javax.swing.JTextField txtselectB;
    private javax.swing.JTextField txtselectC;
    private javax.swing.JTextField txtselectD;
    // End of variables declaration//GEN-END:variables
}
