/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Report.Ireport;
import java.awt.GridBagLayout;

/**
 *
 * @author TMK_PLAN4
 */
public class ReportForm extends javax.swing.JPanel {

    GridBagLayout layout = new GridBagLayout();

    public ReportForm() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        pnAdminLeft = new javax.swing.JPanel();
        btnClassReport = new javax.swing.JButton();
        btnExamReport = new javax.swing.JButton();
        btnResultReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        jMenuItem2.setText("jMenuItem2");

        jMenu9.setText("File");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar5.add(jMenu10);

        setMinimumSize(new java.awt.Dimension(1350, 720));
        setPreferredSize(new java.awt.Dimension(1350, 720));
        setLayout(new java.awt.BorderLayout());

        pnAdminLeft.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnAdminLeft.setMinimumSize(new java.awt.Dimension(200, 100));
        pnAdminLeft.setPreferredSize(new java.awt.Dimension(1350, 680));

        btnClassReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report_1.png"))); // NOI18N
        btnClassReport.setText("Class Report");
        btnClassReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassReportActionPerformed(evt);
            }
        });

        btnExamReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report_1.png"))); // NOI18N
        btnExamReport.setText("Subject Report");
        btnExamReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExamReportActionPerformed(evt);
            }
        });

        btnResultReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report_1.png"))); // NOI18N
        btnResultReport.setText("Result Report");
        btnResultReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnAdminLeftLayout = new javax.swing.GroupLayout(pnAdminLeft);
        pnAdminLeft.setLayout(pnAdminLeftLayout);
        pnAdminLeftLayout.setHorizontalGroup(
            pnAdminLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAdminLeftLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnAdminLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnResultReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnAdminLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnExamReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClassReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(1083, Short.MAX_VALUE))
        );
        pnAdminLeftLayout.setVerticalGroup(
            pnAdminLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAdminLeftLayout.createSequentialGroup()
                .addGroup(pnAdminLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnAdminLeftLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnExamReport)
                        .addGap(18, 18, 18)
                        .addComponent(btnClassReport)))
                .addGap(18, 18, 18)
                .addComponent(btnResultReport)
                .addGap(0, 485, Short.MAX_VALUE))
        );

        add(pnAdminLeft, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClassReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassReportActionPerformed
        // TODO add your handling code here:
        try {
            Ireport ir = new Ireport();
            ir.showJasper("src/Report/reportClass.jasper");
        } catch (Exception ex) {
            ex.getStackTrace();
        }
    }//GEN-LAST:event_btnClassReportActionPerformed

    private void btnExamReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExamReportActionPerformed
        // TODO add your handling code here:
        try {
            Ireport ir = new Ireport();
            ir.showJasper("src/Report/reportExam.jasper");
        } catch (Exception ex) {
            ex.getStackTrace();
        }

    }//GEN-LAST:event_btnExamReportActionPerformed

    private void btnResultReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultReportActionPerformed
        try {
            Ireport ir = new Ireport();
            ir.showJasper("src/Report/reportResult.jasper");
        } catch (Exception ex) {
            ex.getStackTrace();
        }
    }//GEN-LAST:event_btnResultReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClassReport;
    private javax.swing.JButton btnExamReport;
    private javax.swing.JButton btnResultReport;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel pnAdminLeft;
    // End of variables declaration//GEN-END:variables
}
