/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAOT.ConnectionManager;
import DAOT.ResultDao;
import DAOT.UserInformation;
import DAOT.alert_messager;
import DTO.AnswerDto;
import DTO.Question;
import DTO.ResultDto;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author dell
 */
public class Test_Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    private boolean isIt = false;//timer
    private int currentQuestion = 0;
    public static int totalQuestion;
    public static int correct;
    public static float diemThi;
    List<Question> listCauhoi = new ArrayList<>();
    List<AnswerDto> listTraLoi = new ArrayList<>();
    AnswerDto answerDto;
    alert_messager alt = new alert_messager();
    java.util.Timer timer;

    public Test_Test() {
        initComponents();
        SetDeThiInfo();
        tmrQuizTime_Tick();
        btnClear.setEnabled(false);
        btnBack.setEnabled(false);
        btnsubmit.setEnabled(false);
        btnLogOut.setEnabled(false);
        setForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnnext = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbTimeRemaition = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtquestioncontent = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        anwA = new javax.swing.JRadioButton();
        anwd = new javax.swing.JRadioButton();
        anwc = new javax.swing.JRadioButton();
        anwb = new javax.swing.JRadioButton();
        btnClear = new javax.swing.JButton();
        lbcurrentquestion = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbtongcau = new javax.swing.JLabel();
        lbmonhoc = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1365, 741));

        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 680));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setMinimumSize(new java.awt.Dimension(1350, 720));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));
        jPanel3.setMinimumSize(new java.awt.Dimension(366, 152));

        btnnext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Next-icon (1).png"))); // NOI18N
        btnnext.setText("Next");
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnsubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/submit.png"))); // NOI18N
        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Previous-icon.png"))); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/power-button.png"))); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnnext)
                .addGap(58, 58, 58)
                .addComponent(btnsubmit)
                .addGap(49, 49, 49)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsubmit)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(860, 115));

        lbTimeRemaition.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTimeRemaition.setForeground(new java.awt.Color(255, 102, 0));
        lbTimeRemaition.setText("0:00");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/question.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 110, Short.MAX_VALUE)
                .addComponent(lbTimeRemaition, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lbTimeRemaition, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Question detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel5.setMinimumSize(new java.awt.Dimension(1350, 570));

        txtquestioncontent.setEditable(false);
        txtquestioncontent.setColumns(20);
        txtquestioncontent.setLineWrap(true);
        txtquestioncontent.setRows(5);
        txtquestioncontent.setText("question content");
        txtquestioncontent.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtquestioncontent);

        buttonGroup1.add(anwA);
        anwA.setText(" A");
        anwA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anwAActionPerformed(evt);
            }
        });

        buttonGroup1.add(anwd);
        anwd.setText("D");
        anwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anwdActionPerformed(evt);
            }
        });

        buttonGroup1.add(anwc);
        anwc.setText("C");
        anwc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anwcActionPerformed(evt);
            }
        });

        buttonGroup1.add(anwb);
        anwb.setText("B");
        anwb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anwbActionPerformed(evt);
            }
        });

        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/if_edit-clear_118917.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anwc)
                    .addComponent(anwb)
                    .addComponent(anwd)
                    .addComponent(anwA)
                    .addComponent(btnClear))
                .addContainerGap(605, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anwA)
                .addGap(18, 18, 18)
                .addComponent(anwb)
                .addGap(18, 18, 18)
                .addComponent(anwc)
                .addGap(27, 27, 27)
                .addComponent(anwd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        lbcurrentquestion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbcurrentquestion.setText("Cau 1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbcurrentquestion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lbcurrentquestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Ques Total:");

        lbtongcau.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbtongcau.setForeground(new java.awt.Color(255, 102, 0));
        lbtongcau.setText("jLabel8");

        lbmonhoc.setForeground(new java.awt.Color(255, 102, 0));
        lbmonhoc.setText("jLabel2");

        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("Subject:");

        lbtime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbtime.setForeground(new java.awt.Color(255, 102, 0));
        lbtime.setText("0:00");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Exam Time :");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/test1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbtongcau)
                            .addComponent(lbmonhoc))
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addComponent(lbtime, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(lbmonhoc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbtongcau)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lbtime))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1345, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void SetDeThiInfo() {
        lbtime.setText(String.valueOf(HomeTest.thoiGianThi));
        lbmonhoc.setText(HomeTest.monHoc);
        lbtongcau.setText(String.valueOf(HomeTest.tongCau));
    }

    /*dong ho dem nguoc thoi gian*/
    private void tmrQuizTime_Tick() {
        timer = new java.util.Timer();// new time 
        int examTimeminute = Integer.valueOf(lbtime.getText()); // vd : set time counter 5s , se lay tu de thi getlabetExamTime
        HomeTest.thoiGianThi = examTimeminute * 60;
        TimerTask task = new TimerTask() {
            @Override
            public void run() {
                HomeTest.thoiGianThi--;
                int minute = HomeTest.thoiGianThi / 60;
                int Second = HomeTest.thoiGianThi - minute * 60;
                String time = +minute + ":" + Second;
                lbTimeRemaition.setText(time); // time lable show
                if (minute == 0 && Second == 0) {
                    timer.cancel();
                    alt.alter("thoi gian da het , nhan ok de xem ket qua");
                    CheckResult();
                    AddResult();
                    writePdfUsingIText();
                    btnBack.setEnabled(false);
                    btnnext.setEnabled(false);
                    btnsubmit.setEnabled(false);
                    btnClear.setEnabled(false);
                    anwA.setEnabled(false);
                    anwb.setEnabled(false);
                    anwc.setEnabled(false);
                    anwd.setEnabled(false);
                    btnLogOut.setEnabled(true);
                } else if (isIt) { // dung cai nay de stop timer (isIt=true)
                    timer.cancel();
                    isIt = false;
                }
            }
        };
        timer.scheduleAtFixedRate(task, 1000, 1000);
    }

    public void LoadQuestion(String maDe) {
        try {
            String sql = "{call ups_getQuizListBymadethi ('" + maDe + "')}";
            CallableStatement conn = ConnectionManager.getConnection().prepareCall(sql);
            ResultSet rs = conn.executeQuery();
            while (rs.next()) {
                Question ques = new Question();
                ques.setQuesion(rs.getString("ndcauhoi"));
                ques.setAnsw1(rs.getString("phuonganA"));
                ques.setAnsw2(rs.getString("phuonganB"));
                ques.setAnsw3(rs.getString("phuonganC"));
                ques.setAnsw4(rs.getString("phuonganD"));
                ques.setThoigianthi(rs.getInt("thoigianthi"));
                ques.setDapan(rs.getString("dapan"));
                listCauhoi.add(ques);
            }
        } catch (SQLException e) {
            System.out.println("Test_Test.loadQuestion() :" + e.getMessage());
        }
        totalQuestion = listCauhoi.size();
        // add answer default
        for (int i = 0; i < totalQuestion; i++) {
            listTraLoi.add(new AnswerDto(i, "NOT", 0));
        }
    }
    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        if (listCauhoi.size() != listTraLoi.size()) {
            alt.alter("You haven't yet answer all question.");
            System.out.println("list cau chon: " + listTraLoi.size());
        }
        if (listCauhoi.size() == listTraLoi.size()) {
            alt.alter("Are you sure want to submit?");
            CheckResult();
            AddResult();
            writePdfUsingIText();
            btnBack.setEnabled(false);
            btnnext.setEnabled(false);
            btnsubmit.setEnabled(false);
            btnClear.setEnabled(false);
            anwA.setEnabled(false);
            anwb.setEnabled(false);
            anwc.setEnabled(false);
            anwd.setEnabled(false);
            timer.cancel();
            btnLogOut.setEnabled(true);

        }
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed

        if (Check_Answer() == 0) {
            alt.alter("you haven't yet select answer.");
        }
        if (Check_Answer() == 1) {
            if (currentQuestion <= listCauhoi.size() - 2) {
                currentQuestion++;
                btnBack.setEnabled(true);
                /* start Kiem tra cau hoi da duoc tra loi hay chua?*/
                String c = listTraLoi.get(currentQuestion).getPaTraLoi();
                /* end Kiem tra cau hoi da duoc tra loi hay chua?*/
                if (c != "NOT") {
                    showQuestion(currentQuestion);
                    listAlreadyAnswer(currentQuestion);//neu co cau tra loi roi thi khong clear button group
                }
                if (c == "NOT") {
                    showQuestion(currentQuestion);
                    buttonGroup1.clearSelection();
                }
                btnClear.setEnabled(false);

            } else {
                btnnext.setEnabled(false);
                btnsubmit.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnnextActionPerformed

    private void anwAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anwAActionPerformed

        btnClear.setEnabled(true);
        try {
            saveAnswer(currentQuestion, new AnswerDto(currentQuestion, "A", 1));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_anwAActionPerformed

    private void anwbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anwbActionPerformed
        btnClear.setEnabled(true);
        try {
            saveAnswer(currentQuestion, new AnswerDto(currentQuestion, "B", 1));
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_anwbActionPerformed

    private void anwcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anwcActionPerformed
        btnClear.setEnabled(true);
        try {
            saveAnswer(currentQuestion, new AnswerDto(currentQuestion, "C", 1));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_anwcActionPerformed

    private void anwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anwdActionPerformed
        btnClear.setEnabled(true);
        try {
            saveAnswer(currentQuestion, new AnswerDto(currentQuestion, "D", 1));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_anwdActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        buttonGroup1.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        if (currentQuestion <= listCauhoi.size() - 1) {
            btnnext.setEnabled(true);
            currentQuestion--;
            /* start Kiem tra cau hoi da duoc tra loi hay chua?*/
            String c = listTraLoi.get(currentQuestion).getPaTraLoi();
            /* end Kiem tra cau hoi da duoc tra loi hay chua?*/
            if (c != "NOT") {
                showQuestion(currentQuestion);
                listAlreadyAnswer(currentQuestion);// load dap an cua cau da tra loi
                btnClear.setEnabled(true);
            }
            if (c == "NOT") {
                showQuestion(currentQuestion);
                btnClear.setEnabled(false);
            }

        }
        if (currentQuestion <= 0) {
            this.btnBack.setEnabled(false);
        }


    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        Login lg = new Login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void setForm() {
        LoadQuestion(HomeTest.maDe);
        showQuestion(0); // load first question init();
    }

    /*Lay dap an da chon tu list cau tra loi*/
    private void listAlreadyAnswer(int currentQu) {
        if (listTraLoi.get(currentQu).getPaTraLoi().equals("A")) {
            anwA.setSelected(true);
        }
        if (listTraLoi.get(currentQu).getPaTraLoi().equals("B")) {
            anwb.setSelected(true);
        }
        if (listTraLoi.get(currentQu).getPaTraLoi().equals("C")) {
            anwc.setSelected(true);
        }
        if (listTraLoi.get(currentQu).getPaTraLoi().equals("D")) {
            anwd.setSelected(true);
        }

    }

    // Show question into form
    private void showQuestion(int cauSo) {
        Question question = listCauhoi.get(cauSo);
        System.out.println("cau hoi : " + question);
        txtquestioncontent.setText(question.getQuesion());
        anwA.setText(" Answer A :   " + question.getAnsw1());
        anwb.setText(" Answer B :   " + question.getAnsw2());
        anwc.setText(" Answer C :   " + question.getAnsw3());
        anwd.setText(" Answer D :   " + question.getAnsw4());
        lbcurrentquestion.setText("Question : " + (cauSo + 1));
        lbtongcau.setText("<html>" + (cauSo + 1) + "/<b style=\"color:red\">" + totalQuestion + "</b><hmtl>");
    }

    private int Check_Answer() {

        if (anwA.isSelected() || anwb.isSelected() || anwc.isSelected() || anwd.isSelected()) {
            return 1;
        }
        return 0;
    }

    private void saveAnswer(int index, AnswerDto answer) {
        listTraLoi.remove(index);
        listTraLoi.add(index, answer);
    }

    private int CheckResult() {
        correct = 0;
        for (int i = 0; i < totalQuestion; i++) {
            String dapan = listCauhoi.get(i).getDapan().trim();
            String chon = listTraLoi.get(i).getPaTraLoi().trim();
            System.out.println("So sanh cau" + i + " : " + dapan + "@" + chon);
            if (chon.equals(dapan)) {
                correct++;
            } else {
                System.out.println("khong dung");
            }
        }
        return correct;
    }

    private void AddResult() {
        int matk = UserInformation.userID;
        int madethi = Integer.valueOf(HomeTest.maDe);
        diemThi = (10 / totalQuestion) * correct;
        DecimalFormat df = new DecimalFormat("#.##");
        String dx = df.format(diemThi);
        diemThi = Float.valueOf(dx);
        java.sql.Date date = new java.sql.Date(Calendar.getInstance().getTime().getTime());//get current time       
        ResultDto dto = new ResultDto(matk, madethi, diemThi, date);
        System.out.println(" result :" + dto);
        ResultDao dao = new ResultDao();
        boolean isAddResult = dao.addResult(dto);
        if (isAddResult) {
            alt.alter("Submit is Success ,Please click ok to show result.");
        } else {
            alt.alter("Submit faild , Please check with your admin.");
        }
    }

    public void writePdfUsingIText() {
        JFileChooser dialog = new JFileChooser();
        int dialogResult = dialog.showSaveDialog(null);
        if (dialogResult == JFileChooser.APPROVE_OPTION) {
            String filePath = dialog.getSelectedFile().getPath() + ".pdf";
            Document document = new Document();
            try {
                Font code = new Font(Font.FontFamily.COURIER, 12, Font.NORMAL, BaseColor.RED);
                PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(filePath));
                //open
                document.open();
                //set header
                PdfPTable header = new PdfPTable(1);
                //set footer
                PdfPTable footer = new PdfPTable(1);
                // add text header
                PdfPCell text = new PdfPCell();
                text.setPaddingBottom(15);
                text.setPaddingLeft(10);
                text.setBorder(Rectangle.BOTTOM);
                text.setBorderColor(BaseColor.LIGHT_GRAY);
                text.addElement(new Phrase("CNC Aptech", code));
                text.addElement(new Phrase("www.cncaptech.edu.vn", code));
                header.addCell(text);
                document.add(header);
                // start content
                //title
                Paragraph p = new Paragraph();
                p.add("Your Exam Result");
                p.setAlignment(Element.ALIGN_CENTER);
                p.setFont(code);
                document.add(p);
                // information
                Paragraph p2 = new Paragraph();
                p2.add("Name: " + UserInformation.name); //no alignment
                p2.setIndentationLeft(50); // tab left
                p2.setFont(code);
                document.add(p2);
                Paragraph p3 = new Paragraph();
                p3.add("Class: " + UserInformation.classID); //no alignment
                p3.setIndentationLeft(50); // tab left
                p3.setFont(code);
                document.add(p3);
                Paragraph p4 = new Paragraph();
                p4.add("Subject: " + UserInformation.subjectID); //no alignment
                p4.setSpacingAfter(35); // Enter 50 row
                p4.setIndentationLeft(50); // tab left
                p4.setFont(code);
                document.add(p4);
                //table resule
                PdfPTable table = new PdfPTable(4); // 4 columns.
                PdfPCell cell1 = new PdfPCell(new Paragraph("Quiz ID"));
                PdfPCell cell2 = new PdfPCell(new Paragraph("Question Total"));
                PdfPCell cell3 = new PdfPCell(new Paragraph("Question Correct"));
                PdfPCell cell4 = new PdfPCell(new Paragraph("Question Score"));
                PdfPCell cell5 = new PdfPCell(new Paragraph(HomeTest.maDe));
                PdfPCell cell6 = new PdfPCell(new Paragraph(String.valueOf(totalQuestion)));
                PdfPCell cell7 = new PdfPCell(new Paragraph(String.valueOf(correct)));
                PdfPCell cell8 = new PdfPCell(new Paragraph(String.valueOf(diemThi)));
                table.addCell(cell1);
                table.addCell(cell2);
                table.addCell(cell3);
                table.addCell(cell4);
                table.addCell(cell5);
                table.addCell(cell6);
                table.addCell(cell7);
                table.addCell(cell8);
                document.add(table);
                //detail tile
                Paragraph detail = new Paragraph();
                detail.setSpacingBefore(35);
                detail.add("Detail Exam");
                detail.setAlignment(Element.ALIGN_CENTER);
                detail.setFont(code);
                document.add(detail);
                //detail exam
                for (int i = 0; i < listCauhoi.size(); i++) {
                    Question question = listCauhoi.get(i);
                    String paTraLoi = listTraLoi.get(i).getPaTraLoi();
                    //content Question
                    Paragraph pi = new Paragraph();
                    pi.add("Question " + (i + 1) + ": " + question.getQuesion()); //no alignment
                    pi.setSpacingAfter(5);
                    pi.setIndentationLeft(50); // tab left
                    document.add(pi);
                    // answer A
                    Paragraph pi2 = new Paragraph();
                    pi2.add("A. " + question.getAnsw1());
                    pi2.setSpacingAfter(5);
                    pi2.setIndentationLeft(100); // tab left
                    document.add(pi2);
                    //answer B
                    Paragraph pi3 = new Paragraph();
                    pi3.add("B. " + question.getAnsw2());
                    pi3.setSpacingAfter(5);
                    pi3.setIndentationLeft(100); // tab left
                    document.add(pi3);
                    //answer C
                    Paragraph pi4 = new Paragraph();
                    pi4.add("C. " + question.getAnsw3());
                    pi4.setSpacingAfter(5);
                    pi4.setIndentationLeft(100); // tab left
                    document.add(pi4);
                    //answer D
                    Paragraph pi5 = new Paragraph();
                    pi5.add("D. " + question.getAnsw4());
                    pi5.setSpacingAfter(5);
                    pi5.setIndentationLeft(100); // tab left                   
                    document.add(pi5);
                    //correct anser
                    Paragraph pi6 = new Paragraph();
                    pi6.add("Correct Answer. " + question.getDapan());
                    pi6.setSpacingAfter(5);
                    pi6.setIndentationLeft(100); // tab left                   
                    document.add(pi6);
                    //your answer
                    Paragraph pi7 = new Paragraph();
                    pi7.add("Your Answer. " + paTraLoi);
                    pi7.setSpacingAfter(5);
                    pi7.setIndentationLeft(100); // tab left                   
                    document.add(pi7);
                }
                //set footer
                PdfPCell textF = new PdfPCell();
                textF.setPaddingBottom(15);
                textF.setPaddingLeft(10);
                textF.setBorder(Rectangle.TOP);
                textF.setBorderColor(BaseColor.LIGHT_GRAY);
                textF.addElement(new Phrase("@version 1.0", code));
                footer.addCell(textF);
                document.add(footer);
                //close
                document.close();
                alert_messager alt = new alert_messager();
                alt.alter("Export Done");
                // open after save
                try {
                    Desktop.getDesktop().open(new File(filePath));
                } catch (IOException ex) {
                    Logger.getLogger(Test_Test.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("Done");

            } catch (Exception e) {
                System.out.println("err :" + e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test_Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton anwA;
    private javax.swing.JRadioButton anwb;
    private javax.swing.JRadioButton anwc;
    private javax.swing.JRadioButton anwd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnsubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTimeRemaition;
    private javax.swing.JLabel lbcurrentquestion;
    private javax.swing.JLabel lbmonhoc;
    public static javax.swing.JLabel lbtime;
    private javax.swing.JLabel lbtongcau;
    private javax.swing.JTextArea txtquestioncontent;
    // End of variables declaration//GEN-END:variables
}
