package entities;
// Generated Aug 12, 2018 6:18:05 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DeThi generated by hbm2java
 */
@Entity
@Table(name = "DeThi", schema = "dbo", catalog = "QLTTN")
public class DeThi implements java.io.Serializable {

	private Integer madethi;
	private String mamonhoc;
	private Integer socaudokho1;
	private Integer socaudokho2;
	private Integer socaudokho3;
	private Long tongdiem;
	private Integer thoigianthi;
	private int trangthai;
	private Set<CauHoi> cauHois = new HashSet<CauHoi>(0);
	private Set<KetQua> ketQuas = new HashSet<KetQua>(0);

	public DeThi() {
	}

	public DeThi(String mamonhoc, int trangthai) {
		this.mamonhoc = mamonhoc;
		this.trangthai = trangthai;
	}

	public DeThi(String mamonhoc, Integer socaudokho1, Integer socaudokho2, Integer socaudokho3, Long tongdiem,
			Integer thoigianthi, int trangthai, Set<CauHoi> cauHois, Set<KetQua> ketQuas) {
		this.mamonhoc = mamonhoc;
		this.socaudokho1 = socaudokho1;
		this.socaudokho2 = socaudokho2;
		this.socaudokho3 = socaudokho3;
		this.tongdiem = tongdiem;
		this.thoigianthi = thoigianthi;
		this.trangthai = trangthai;
		this.cauHois = cauHois;
		this.ketQuas = ketQuas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "madethi", unique = true, nullable = false)
	public Integer getMadethi() {
		return this.madethi;
	}

	public void setMadethi(Integer madethi) {
		this.madethi = madethi;
	}

	@Column(name = "mamonhoc", nullable = false, length = 10)
	public String getMamonhoc() {
		return this.mamonhoc;
	}

	public void setMamonhoc(String mamonhoc) {
		this.mamonhoc = mamonhoc;
	}

	@Column(name = "socaudokho1")
	public Integer getSocaudokho1() {
		return this.socaudokho1;
	}

	public void setSocaudokho1(Integer socaudokho1) {
		this.socaudokho1 = socaudokho1;
	}

	@Column(name = "socaudokho2")
	public Integer getSocaudokho2() {
		return this.socaudokho2;
	}

	public void setSocaudokho2(Integer socaudokho2) {
		this.socaudokho2 = socaudokho2;
	}

	@Column(name = "socaudokho3")
	public Integer getSocaudokho3() {
		return this.socaudokho3;
	}

	public void setSocaudokho3(Integer socaudokho3) {
		this.socaudokho3 = socaudokho3;
	}

	@Column(name = "tongdiem", precision = 10, scale = 0)
	public Long getTongdiem() {
		return this.tongdiem;
	}

	public void setTongdiem(Long tongdiem) {
		this.tongdiem = tongdiem;
	}

	@Column(name = "thoigianthi")
	public Integer getThoigianthi() {
		return this.thoigianthi;
	}

	public void setThoigianthi(Integer thoigianthi) {
		this.thoigianthi = thoigianthi;
	}

	@Column(name = "trangthai", nullable = false)
	public int getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(int trangthai) {
		this.trangthai = trangthai;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "deThis")
	public Set<CauHoi> getCauHois() {
		return this.cauHois;
	}

	public void setCauHois(Set<CauHoi> cauHois) {
		this.cauHois = cauHois;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deThi")
	public Set<KetQua> getKetQuas() {
		return this.ketQuas;
	}

	public void setKetQuas(Set<KetQua> ketQuas) {
		this.ketQuas = ketQuas;
	}

}
