package entities;
// Generated Aug 12, 2018 6:18:05 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KetQua generated by hbm2java
 */
@Entity
@Table(name = "KetQua", schema = "dbo", catalog = "QLTTN")
public class KetQua implements java.io.Serializable {

	private Integer makq;
	private DeThi deThi;
	private TaiKhoan taiKhoan;
	private double diemThi;
	private Date ngaythi;

	public KetQua() {
	}

	public KetQua(DeThi deThi, TaiKhoan taiKhoan, double diemThi, Date ngaythi) {
		this.deThi = deThi;
		this.taiKhoan = taiKhoan;
		this.diemThi = diemThi;
		this.ngaythi = ngaythi;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "makq", unique = true, nullable = false)
	public Integer getMakq() {
		return this.makq;
	}

	public void setMakq(Integer makq) {
		this.makq = makq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "madethi", nullable = false)
	public DeThi getDeThi() {
		return this.deThi;
	}

	public void setDeThi(DeThi deThi) {
		this.deThi = deThi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matk", nullable = false)
	public TaiKhoan getTaiKhoan() {
		return this.taiKhoan;
	}

	public void setTaiKhoan(TaiKhoan taiKhoan) {
		this.taiKhoan = taiKhoan;
	}

	@Column(name = "diemThi", nullable = false, precision = 53, scale = 0)
	public double getDiemThi() {
		return this.diemThi;
	}

	public void setDiemThi(double diemThi) {
		this.diemThi = diemThi;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaythi", nullable = false, length = 23)
	public Date getNgaythi() {
		return this.ngaythi;
	}

	public void setNgaythi(Date ngaythi) {
		this.ngaythi = ngaythi;
	}

}
