package entities;
// Generated Aug 12, 2018 6:18:05 PM by Hibernate Tools 5.2.0.Beta1


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MonHoc generated by hbm2java
 */
@Entity
@Table(name = "MonHoc", schema = "dbo", catalog = "QLTTN")
public class MonHoc implements java.io.Serializable {

	private String mamonhoc;
	private String tenmonhoc;
	private Integer sotinchi;
	private Integer trangthai;
	private List<CauHoi> cauHois = new ArrayList<CauHoi>();
	private List<TaiKhoan> taiKhoans = new ArrayList<TaiKhoan>();

	public MonHoc() {
	}

	public MonHoc(String mamonhoc) {
		this.mamonhoc = mamonhoc;
	}

	public MonHoc(String mamonhoc, String tenmonhoc, Integer sotinchi, Integer trangthai, List<CauHoi> cauHois,
			List<TaiKhoan> taiKhoans) {
		this.mamonhoc = mamonhoc;
		this.tenmonhoc = tenmonhoc;
		this.sotinchi = sotinchi;
		this.trangthai = trangthai;
		this.cauHois = cauHois;
		this.taiKhoans = taiKhoans;
	}

	@Id

	@Column(name = "mamonhoc", unique = true, nullable = false, length = 10)
	public String getMamonhoc() {
		return this.mamonhoc;
	}

	public void setMamonhoc(String mamonhoc) {
		this.mamonhoc = mamonhoc;
	}

	@Column(name = "tenmonhoc")
	public String getTenmonhoc() {
		return this.tenmonhoc;
	}

	public void setTenmonhoc(String tenmonhoc) {
		this.tenmonhoc = tenmonhoc;
	}

	@Column(name = "sotinchi")
	public Integer getSotinchi() {
		return this.sotinchi;
	}

	public void setSotinchi(Integer sotinchi) {
		this.sotinchi = sotinchi;
	}

	@Column(name = "trangthai")
	public Integer getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Integer trangthai) {
		this.trangthai = trangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "monHoc")
	public List<CauHoi> getCauHois() {
		return this.cauHois;
	}

	public void setCauHois(List<CauHoi> cauHois) {
		this.cauHois = cauHois;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "monHocs")
	public List<TaiKhoan> getTaiKhoans() {
		return this.taiKhoans;
	}

	public void setTaiKhoans(List<TaiKhoan> taiKhoans) {
		this.taiKhoans = taiKhoans;
	}

}
