package entities;
// Generated Aug 12, 2018 6:18:05 PM by Hibernate Tools 5.2.0.Beta1

import java.util.ArrayList;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaiKhoan generated by hbm2java
 */
@Entity
@Table(name = "TaiKhoan", schema = "dbo", catalog = "QLTTN")
public class TaiKhoan implements java.io.Serializable {

	private Integer matk;
	private LopHoc lopHoc;
	private String hoten;
	private Date ngaysinh;
	private String diachi;
	private Integer namhoc;
	private String sdt;
	private String email;
	private String username;
	private String pass;
	private String quyen;
	private Integer trangthai;
	private List<MonHoc> monHocs = new ArrayList<MonHoc>(0);
	private List<KetQua> ketQuas = new ArrayList<KetQua>(0);
	private List<CauHoi> cauHois = new ArrayList<CauHoi>(0);

	public TaiKhoan() {
	}

	public TaiKhoan(String username, String pass, String quyen) {
		this.username = username;
		this.pass = pass;
		this.quyen = quyen;
	}

	public TaiKhoan(LopHoc lopHoc, String hoten, Date ngaysinh, String diachi, Integer namhoc, String sdt,
			String email, String username, String pass, String quyen, Integer trangthai,
			List<MonHoc> monHocs, List<KetQua> ketQuas, List<CauHoi> cauHois) {
		this.lopHoc = lopHoc;
		this.hoten = hoten;
		this.ngaysinh = ngaysinh;
		this.diachi = diachi;
		this.namhoc = namhoc;
		this.sdt = sdt;
		this.email = email;
		this.username = username;
		this.pass = pass;
		this.quyen = quyen;
		this.trangthai = trangthai;
		this.monHocs = monHocs;
		this.ketQuas = ketQuas;
		this.cauHois = cauHois;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "matk", unique = true, nullable = false)
	public Integer getMatk() {
		return this.matk;
	}

	public void setMatk(Integer matk) {
		this.matk = matk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "malophoc")
	public LopHoc getLopHoc() {
		return this.lopHoc;
	}

	public void setLopHoc(LopHoc lopHoc) {
		this.lopHoc = lopHoc;
	}

	@Column(name = "hoten")
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaysinh", length = 23)
	public Date getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(Date ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "diachi")
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "namhoc")
	public Integer getNamhoc() {
		return this.namhoc;
	}

	public void setNamhoc(Integer namhoc) {
		this.namhoc = namhoc;
	}

	@Column(name = "sdt", length = 11)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "pass", nullable = false)
	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	@Column(name = "quyen", nullable = false)
	public String getQuyen() {
		return this.quyen;
	}

	public void setQuyen(String quyen) {
		this.quyen = quyen;
	}

	@Column(name = "trangthai")
	public Integer getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Integer trangthai) {
		this.trangthai = trangthai;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "Thamgia", schema = "dbo", catalog = "QLTTN", joinColumns = {
			@JoinColumn(name = "matk", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "mamonhoc", nullable = false, updatable = false) })
	public List<MonHoc> getMonHocs() {
		return this.monHocs;
	}

	public void setMonHocs(List<MonHoc> monHocs) {
		this.monHocs = monHocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taiKhoan")
	public List<KetQua> getKetQuas() {
		return this.ketQuas;
	}

	public void setKetQuas(List<KetQua> ketQuas) {
		this.ketQuas = ketQuas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taiKhoan")
	public List<CauHoi> getCauHois() {
		return this.cauHois;
	}

	public void setCauHois(List<CauHoi> cauHois) {
		this.cauHois = cauHois;
	}

}
